# Generated by Django 4.2.16 on 2025-03-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='user',
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_front',
            field=models.ImageField(null=True, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id_card', 'National ID Card'), ('driving_license', 'Driving License')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='selfie',
            field=models.ImageField(null=True, upload_to='verification_selfies/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=12),
        ),
    ]
