# Generated by Django 4.2.16 on 2025-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_documenttype_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_url',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
