# Generated by Django 4.2.16 on 2025-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0004_alter_document_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.CharField(max_length=255),
        ),
    ]
